# Generated by Django 2.0.6 on 2018-07-16 18:17

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_task_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='done',
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=app.models.nbr_obj, null=True, unique=True),
        ),
    ]
