# Generated by Django 2.0.6 on 2018-07-16 18:22

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180716_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.PositiveIntegerField(default=app.models.nbr_obj, null=True, unique=True),
        ),
    ]
